language: python

branches:
  only:
  - /./       # Matches all the branches
  - gh-pages  # Explicitly allow gh-pages

python:
  - 2.7
  - 3.4
  - 3.5

install:
  - pip install pyyaml

script:
  - python parse_entries.py
